# Generated by Django 4.1.7 on 2023-02-17 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_alter_line_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('READY', 'READY'), ('ACCEPTED', 'ACCEPTED'), ('IN_PROGRESS', 'IN PROGRESS'), ('DONE', 'DONE'), ('CANCELLED', 'CANCELLED')], default='NEW', max_length=30),
        ),
    ]
