# Generated by Django 4.1.7 on 2023-02-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_line_is_skipped_alter_line_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="product_price",
            field=models.FloatField(default=0),
        ),
    ]
