# Generated by Django 4.1.6 on 2023-02-10 10:55

from django.db import migrations, models
import task.validators


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_alter_comment_level_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[task.validators.validate_level]
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
