# Generated by Django 4.1.6 on 2023-02-13 10:07

from django.db import migrations, models
import django.db.models.deletion
import task.validators


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0004_rename_creator_id_comment_creator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[task.validators.validate_level]
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="task.task",
            ),
        ),
    ]
