# Generated by Django 4.1.6 on 2023-02-14 09:51

from django.db import migrations, models
import task.validators


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0005_alter_comment_level_alter_comment_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[task.validators.validate_level]
            ),
        ),
    ]
